---
- hosts: all
  sudo: true
  tasks: 
    - name: Update Ubuntu Server 
      apt: update_cache=true
  #  - name: Upgrade Ubuntu Server
  #    apt: upgrade=yes
    - name: Install libpq-dev
      apt: pkg=libpq-dev state=installed
    - name: Install python-setuptools
      apt: pkg=python-setuptools state=installed
    - name: Install python-dev
      apt: pkg=python-dev state=installed
    - name: Install pip
      apt: pkg=python-pip state=installed 
    - name: Create requirements directory ifNotExists
      file: path=requirements state=directory
    - name: Copy the local pip requirements file
      copy: src=../requirements/requirements.txt dest=requirements/requirements.txt
    - name: Install python package requirements
      command: sudo pip install -r requirements/requirements.txt
    - name: Installs nginx web server
      apt: pkg=nginx state=installed 
    - name: install postgresql
      apt: pkg=postgresql state=installed
    - name: Install postgresql-contrib 
      apt: pkg=postgresql-contrib 
    - name: Install supervisor
      apt: pkg=supervisor state=installed
    - name: Congfigure postgresql
      script: postgres/config_postgres.sh
    - name: Configure nginx 
      copy: src=nginx/djangoseller dest=/etc/nginx/sites-available/djangoseller
    - name: Create symlinks
      file: src=/etc/nginx/sites-available/djangoseller dest=/etc/nginx/sites-enabled/djangoseller state=link
    - name: Delete default nginx config file.
      file: path=/etc/nginx/sites-enabled/default state=absent
    - name: Create gunicorn directories
      file: path=/home/root/www/gunicorn state=directory
    - name: Configure gunicorn 
      copy: src=gunicorn/conf.py dest=/home/root/www/gunicorn/conf.py
    - name: Create supervisor directories
      file: path=/etc/supervisor/conf.d state=directory
    - name: Create supervisor gunicorn log directories
      file: path=/var/log/supervisor/gunicorn state=directory
    - name: Configure supervisor
      copy: src=supervisor/gunicorn.conf dest=/etc/supervisor/conf.d/gunicorn.conf
    - name: Create Django static directory
      file: path=/home/root/www/static state=directory
    - name: Create Django media directory
      file: path=/home/root/www/media/ state=directory
    - name: Create working tree directory
      file: path=/home/root/www/website state=directory
    - name: Restart nginx
      service: name=nginx state=restarted 
    - name: Restart supervisor
      command: service supervisor restart
    - name: Restart gunicorn
      supervisorctl: name=gunicorn state=restarted config=/etc/supervisor/conf.d/gunicorn.conf
