---
- hosts: djangoseller.com
  tasks:
#    - name: Updates a server 
#      apt: update_cache=true
    - name: Install libpq-dev
      apt: pkg=libpq-dev state=installed
    - name: Install python-setuptools
      apt: pkg=python-setuptools state=installed
    - name: Install python-dev
      apt: pkg=python-dev state=installed
    - name: Install pip
      apt: pkg=python-pip state=installed 
    - name: Create requirements directory ifNotExists
      file: path=requirements state=directory
    - name: Copy the local pip requirements file
      copy: src=../requirements/requirements.txt dest=requirements/requirements.txt
    - name: Install python package requirements
      command: sudo pip install -r requirements/requirements.txt
    - name: Installs nginx web server
      apt: pkg=nginx state=installed 
      notify:
        - start nginx
    - name: install postgresql
      apt: pkg=postgresql state=installed
    - name: Install postgresql-contrib 
      apt: pkg=postgresql-contrib 
    - name: Create postgresql database
      script: provision.sh
  handlers:
    - name: start nginx
      service: name=nginx state=started
