---
- hosts: djangoseller.com
  task:
    - name: Updates a server 
      apt: update_cache=true
    - name: Upgrades a server
      apt: upgrade=full
    - name: Installs nginx web server
      apt: pkg=nginx state=installed 
      notify:
        - start nginx
    - name: Install pip
      apt: pkg=python-pip state=installed 
    - name: Install pip requirements
      pip: 
  handlers:
    - name: start nginx
      service: name=nginx state=started
